# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  
  zalenium:
    image: "dosel/zalenium"
    container_name: selenium-grid_mobile-sample
    hostname: selenium-grid_mobile-sample
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - BROWSER_STACK_USER=${bs_user}
      - BROWSER_STACK_KEY=${bs_key}
    command: >
      start --desiredContainers 0
            --maxDockerSeleniumContainers 4
            --timeZone "America/Argentina/Buenos_Aires"
            --browserStackEnabled true  

  nginx_web-sample:
    image: nginx:stable
    volumes:
      - ./docker/jenkins_home/reportsVolume:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    environment:
      - TZ=America/Argentina/Buenos_Aires